# Generated by Django 4.2.5 on 2023-09-19 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='date_added',
        ),
    ]
